-- Migration 040: Performance indexes for list endpoints + missing thumbnail_url column
--
-- Run in the Supabase SQL Editor. Idempotent (IF NOT EXISTS everywhere).
--
-- Context:
--   * list_jobs_scoped filters video_jobs by user_id (+ optional project_id)
--     ordered by created_at DESC on every dashboard/videos-page load — there
--     is no user_id index today, only (project_id, created_at) from 031.
--   * influencers has ZERO indexes; list_influencers_scoped filters by
--     (user_id, project_id) on every page that shows influencer names.
--   * clone_video_jobs is queried by (user_id, created_at DESC) whenever
--     /jobs?include_clones=true is called (dashboard + videos page).
--   * video_jobs.thumbnail_url is already read/written by the code
--     (creative-os jobs-status select + /video-thumbnails caching) but the
--     column never existed — the missing column silently breaks the video
--     status polling select. Adding it fixes polling AND enables poster
--     image caching for video cards.

-- 1. Missing column used by existing code paths
ALTER TABLE public.video_jobs
    ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;

COMMENT ON COLUMN public.video_jobs.thumbnail_url IS
    'First-frame poster image generated by creative-os /video-thumbnails (FFmpeg). Used as <img poster> in galleries so list views never download the MP4.';

-- 2. video_jobs: scoped list queries (user_id [+ project_id], newest first)
CREATE INDEX IF NOT EXISTS idx_video_jobs_user_created
    ON public.video_jobs (user_id, created_at DESC);

-- 3. influencers: scoped lookups (table currently has no indexes at all)
CREATE INDEX IF NOT EXISTS idx_influencers_user_project
    ON public.influencers (user_id, project_id);

-- 4. clone_video_jobs: merged into /jobs?include_clones=true lists
CREATE INDEX IF NOT EXISTS idx_clone_video_jobs_user_created
    ON public.clone_video_jobs (user_id, created_at DESC);
